### ISSUE TITLE
Unexpected XML character after plist update

### ISSUE THREAD

**Issue by jthom-vmray** [citruz/dmgwiz#19]
Some DMGs cannot get parsed anymore with `plist` version 1.5 and crash with the error `error: could not read input file - parse error (UnexpectedXmlCharactersExpectedElement (offset 8359))`.
It looks like the `header.xml_length` (lib.rs:357) is one or two bytes off and the plist ends with and invalid XML character.  Previous `plist` versions before `1.5` seem to not have this problem.
[Example DMG](https://www.virustotal.com/gui/file/4051b1f065a5ad55843ac976573226f4f291e3e1d7e95411653b2ce4ca3e0bda)

**Comment by citruz** [comment]
Fixed in https://github.com/citruz/dmgwiz/pull/16
